spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:8080/elephant_fence
    username: postgres
    password: Gimshi0327*

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true