spring:
  config:
    activate:
      on-profile: prod

server:
  ssl:
    enabled: true
    key-store: ${SSL_KEYSTORE_PATH:classpath:keystore.p12}
    key-store-password: ${SSL_KEYSTORE_PASSWORD:secret}
    key-store-type: PKCS12
  port: 8443

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:https://fence-monitor.nerdc.lk}
