package com.nerdc.elephantfence.backend.reports;
import com.nerdc.elephantfence.backend.reports.service.*;
import com.nerdc.elephantfence.backend.reports.dto.ReportRequest;
import com.nerdc.elephantfence.backend.reports.dto.ReportRequest.*;
import com.nerdc.elephantfence.backend.alerts.service.AlertAccess;
import com.nerdc.elephantfence.backend.users.entity.*;
import org.junit.jupiter.api.*;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.web.server.ResponseStatusException;
import org.apache.pdfbox.Loader;
import org.apache.pdfbox.text.PDFTextStripper;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

class ReportServiceTest {
    ReportService service; NamedParameterJdbcTemplate db; AlertAccess access; User user;
    @BeforeEach void setup() {
        db=new NamedParameterJdbcTemplate(new DriverManagerDataSource("jdbc:h2:mem:"+UUID.randomUUID()+";MODE=PostgreSQL;DB_CLOSE_DELAY=-1","sa",""));
        var jdbc=db.getJdbcTemplate();
        for(String sql:List.of(
            "CREATE TABLE provinces(id BIGINT,name VARCHAR)",
            "CREATE TABLE districts(id BIGINT,name VARCHAR)",
            "CREATE TABLE users(id UUID,full_name VARCHAR)",
            "CREATE TABLE fences(id BIGINT,code VARCHAR,name VARCHAR,province_id BIGINT,district_id BIGINT,primary_maintenance_user_id UUID,health VARCHAR,length_km NUMERIC,average_voltage_kv NUMERIC,updated_at TIMESTAMP WITH TIME ZONE)",
            "CREATE TABLE sections(id BIGINT,fence_id BIGINT,code VARCHAR,status VARCHAR,length_km NUMERIC,voltage_kv NUMERIC,battery INT,updated_at TIMESTAMP WITH TIME ZONE)",
            "CREATE TABLE devices(id BIGINT,name VARCHAR,serial VARCHAR,status VARCHAR,voltage NUMERIC,battery INT,signal INT,enabled BOOLEAN,last_seen TIMESTAMP WITH TIME ZONE,section_id BIGINT,fence_id BIGINT,gateway_id BIGINT)",
            "CREATE TABLE telemetry_readings(device_id BIGINT,voltage_kv NUMERIC,battery INT,signal INT,recorded_at TIMESTAMP WITH TIME ZONE)",
            "CREATE TABLE gateways(id BIGINT,name VARCHAR,serial VARCHAR,status VARCHAR,signal INT,power INT,firmware VARCHAR,enabled BOOLEAN,last_seen TIMESTAMP WITH TIME ZONE)",
            "CREATE TABLE gateway_fences(gateway_id BIGINT,fence_id BIGINT)",
            "CREATE TABLE fence_backup_maintenance_users(fence_id BIGINT,user_id UUID)",
            "CREATE TABLE alerts(id BIGINT,code VARCHAR,title VARCHAR,type VARCHAR,severity VARCHAR,status VARCHAR,assignment_status VARCHAR,created_at TIMESTAMP WITH TIME ZONE,acknowledged_at TIMESTAMP WITH TIME ZONE,resolved_at TIMESTAMP WITH TIME ZONE,fence_id BIGINT,section_id BIGINT,assignee_user_id UUID)",
            "CREATE TABLE alert_events(alert_id BIGINT,event_type VARCHAR,actor_name VARCHAR,details VARCHAR,occurred_at TIMESTAMP WITH TIME ZONE)",
            "CREATE TABLE generated_reports(id BIGINT GENERATED BY DEFAULT AS IDENTITY,name VARCHAR,template_id VARCHAR,generated_by_user_id UUID,date_range_label VARCHAR,status VARCHAR,file_size VARCHAR,format VARCHAR,file_content BYTEA,fence_ids VARCHAR,generated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)",
            "INSERT INTO provinces VALUES(1,'Uva'),(2,'Western')",
            "INSERT INTO districts VALUES(1,'Monaragala'),(2,'Colombo')",
            "INSERT INTO fences(id,code,name,province_id,district_id,health) VALUES(1,'F1','Test Fence',1,1,'HEALTHY'),(2,'F2','Hidden Fence',2,2,'OFFLINE')",
            "INSERT INTO sections(id,fence_id,code) VALUES(1,1,'S1'),(2,2,'S2')",
            "INSERT INTO devices(id,name,section_id,fence_id,gateway_id) VALUES(1,'Sensor',1,1,1)",
            "INSERT INTO gateways(id,name) VALUES(1,'Gateway')",
            "INSERT INTO gateway_fences VALUES(1,1)",
            "INSERT INTO telemetry_readings(device_id,voltage_kv,recorded_at) VALUES(1,7.5,CURRENT_TIMESTAMP),(1,2.1,TIMESTAMP WITH TIME ZONE '2020-01-01 00:00:00+00')",
            "INSERT INTO alerts(id,code,title,fence_id,section_id,created_at) VALUES(1,'ALT-1','Wire break',1,1,CURRENT_TIMESTAMP)",
            "INSERT INTO alert_events(alert_id,event_type,details,occurred_at) VALUES(1,'START_WORK','Repair started',CURRENT_TIMESTAMP)"
        ))jdbc.execute(sql);
        user=User.builder().id(UUID.randomUUID()).fullName("Report Tester").role(Role.FIELD_ADMIN).build();
        db.update("INSERT INTO users VALUES(:id,:name)",Map.of("id",user.getId(),"name",user.getFullName()));
        access=mock(AlertAccess.class);when(access.currentUser()).thenReturn(user);when(access.inScope(user,1L,1L)).thenReturn(true);
        service=new ReportService(db,access,new ReportRenderer());
    }
    ReportRequest request(Template t,Format f){return new ReportRequest(t,new Scope(null,null,null,null),new DateRange("TODAY",null,null),new Options(false,false,false),f);}
    @Test void everyTemplateQueriesRealData() {
        for(var template:Template.values())assertEquals(1,service.preview(request(template,Format.CSV)).get("recordCount"),template.name());
    }
    @Test void persistsCsvAndOwnerHistory() {
        var result=service.generate(request(Template.FENCE_HEALTH,Format.CSV));
        long id=((Number)result.get("id")).longValue();
        String csv=new String(service.download(id).content(),java.nio.charset.StandardCharsets.UTF_8);
        assertTrue(csv.contains("Test Fence"));assertFalse(csv.contains("Hidden Fence"));
        assertEquals(1L,service.history(0).get("total"));
        when(access.currentUser()).thenReturn(User.builder().id(UUID.randomUUID()).role(Role.SUPER_ADMIN).build());
        assertEquals(404,assertThrows(ResponseStatusException.class,()->service.download(id)).getStatusCode().value());
        assertEquals(0L,service.history(0).get("total"));
    }
    @Test void producesReadablePdf() throws Exception {
        long id=((Number)service.generate(request(Template.ALERT_SUMMARY,Format.PDF)).get("id")).longValue();
        try(var pdf=Loader.loadPDF(service.download(id).content())){assertTrue(new PDFTextStripper().getText(pdf).contains("Wire break"));}
    }
    @Test void deniesRevokedLocationAccess() {
        long id=((Number)service.generate(request(Template.FENCE_HEALTH,Format.CSV)).get("id")).longValue();
        when(access.inScope(user,1L,1L)).thenReturn(false);
        assertEquals(403,assertThrows(ResponseStatusException.class,()->service.download(id)).getStatusCode().value());
    }
    @Test void deniesUnpermittedScopeAndWrongSection() {
        var r=request(Template.FENCE_HEALTH,Format.CSV);
        assertThrows(ResponseStatusException.class,()->service.preview(new ReportRequest(r.template(),new Scope(null,null,"F2",null),r.dateRange(),r.options(),r.format())));
        assertThrows(ResponseStatusException.class,()->service.preview(new ReportRequest(r.template(),new Scope(null,null,"F1","S2"),r.dateRange(),r.options(),r.format())));
    }
    @Test void rejectsInvalidDatesAndSupportsEmptyResults() {
        var r=request(Template.FENCE_HEALTH,Format.CSV);
        assertThrows(ResponseStatusException.class,()->service.preview(new ReportRequest(r.template(),r.scope(),new DateRange(null,"2026-01-02","2026-01-01"),r.options(),r.format())));
        when(access.inScope(user,1L,1L)).thenReturn(false);
        assertEquals(0,service.preview(r).get("recordCount"));
    }
    @Test void appendsRequestedHistory() {
        var r=request(Template.FENCE_HEALTH,Format.CSV);
        assertEquals(3,service.preview(new ReportRequest(r.template(),r.scope(),r.dateRange(),new Options(false,true,true),r.format())).get("recordCount"));
    }
    @Test void csvEscapesFormulaAndQuotes() {
        var data=new ReportRenderer.Dataset("Test",List.of(Map.of("name","=HYPERLINK(\"example\")")));
        String csv=new String(new ReportRenderer().csv("Test","Today",List.of(),List.of(data)),java.nio.charset.StandardCharsets.UTF_8);
        assertTrue(csv.contains("'=HYPERLINK"));
        assertTrue(csv.contains("\"\"example\"\""));
    }
}
