CREATE TABLE gateways (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    serial VARCHAR(100) NOT NULL UNIQUE,
    imei VARCHAR(100) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'offline',
    signal INT NOT NULL DEFAULT 0,
    power INT NOT NULL DEFAULT 0,
    firmware VARCHAR(50),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_seen TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_gateways_status CHECK (status IN ('online', 'warning', 'offline'))
);

CREATE TABLE devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gateway_id BIGINT REFERENCES gateways(id) ON DELETE SET NULL,
    name VARCHAR(100) NOT NULL,
    serial VARCHAR(100) NOT NULL UNIQUE,
    type VARCHAR(50) NOT NULL DEFAULT 'Voltage Monitor',
    status VARCHAR(20) NOT NULL DEFAULT 'offline',
    voltage DOUBLE PRECISION,
    signal INT NOT NULL DEFAULT 0,
    battery INT NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_seen TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_devices_status CHECK (status IN ('online', 'warning', 'offline'))
);

CREATE INDEX idx_devices_gateway_id ON devices(gateway_id);
CREATE INDEX idx_devices_status ON devices(status);
CREATE INDEX idx_gateways_status ON gateways(status);
