CREATE TABLE fences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(150) NOT NULL,
    province_id BIGINT NOT NULL REFERENCES provinces(id),
    district_id BIGINT NOT NULL REFERENCES districts(id),
    length_km NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    gateway_id BIGINT REFERENCES gateways(id) ON DELETE SET NULL,
    average_voltage_kv NUMERIC(5, 2),
    health VARCHAR(20) NOT NULL DEFAULT 'OFFLINE',
    primary_maintenance_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_fences_health CHECK (health IN ('HEALTHY', 'WARNING', 'CRITICAL', 'OFFLINE'))
);

CREATE TABLE fence_backup_maintenance_users (
    fence_id BIGINT NOT NULL REFERENCES fences(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (fence_id, user_id)
);

CREATE TABLE gateway_fences (
    gateway_id BIGINT NOT NULL REFERENCES gateways(id) ON DELETE CASCADE,
    fence_id BIGINT NOT NULL REFERENCES fences(id) ON DELETE CASCADE,
    PRIMARY KEY (gateway_id, fence_id)
);

CREATE TABLE sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fence_id BIGINT NOT NULL REFERENCES fences(id) ON DELETE CASCADE,
    code VARCHAR(50) NOT NULL,
    start_gps VARCHAR(100),
    end_gps VARCHAR(100),
    length_km NUMERIC(10, 2) NOT NULL DEFAULT 0.00,
    device_id BIGINT REFERENCES devices(id) ON DELETE SET NULL,
    voltage_kv NUMERIC(5, 2),
    battery INT,
    status VARCHAR(20) NOT NULL DEFAULT 'OFFLINE',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sections_fence_code UNIQUE (fence_id, code),
    CONSTRAINT ck_sections_status CHECK (status IN ('HEALTHY', 'WARNING', 'CRITICAL', 'OFFLINE'))
);

ALTER TABLE devices ADD COLUMN fence_id BIGINT REFERENCES fences(id) ON DELETE SET NULL;
ALTER TABLE devices ADD COLUMN section_id BIGINT REFERENCES sections(id) ON DELETE SET NULL;

CREATE INDEX idx_fences_province_district ON fences(province_id, district_id);
CREATE INDEX idx_fences_primary_maintenance ON fences(primary_maintenance_user_id);
CREATE INDEX idx_sections_fence_id ON sections(fence_id);
CREATE INDEX idx_sections_device_id ON sections(device_id);
