CREATE TABLE telemetry_readings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id BIGINT NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
    voltage_kv NUMERIC(5, 2) NOT NULL,
    battery INT,
    signal INT,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_telemetry_device_recorded ON telemetry_readings(device_id, recorded_at DESC);
CREATE INDEX idx_telemetry_recorded_at ON telemetry_readings(recorded_at DESC);
