CREATE TABLE alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    title VARCHAR(200) NOT NULL,
    type VARCHAR(50) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    province_id BIGINT REFERENCES provinces(id),
    district_id BIGINT REFERENCES districts(id),
    fence_id BIGINT REFERENCES fences(id),
    section_id BIGINT REFERENCES sections(id),
    device_id BIGINT REFERENCES devices(id),
    detected_voltage_kv NUMERIC(5, 2),
    threshold_voltage_kv NUMERIC(5, 2),
    status VARCHAR(30) NOT NULL DEFAULT 'UNACKNOWLEDGED',
    assignment_status VARCHAR(30) NOT NULL DEFAULT 'UNASSIGNED',
    assignment_source VARCHAR(30) NOT NULL DEFAULT 'NONE',
    assignee_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    acknowledged_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    assigned_at TIMESTAMPTZ,
    acceptance_deadline TIMESTAMPTZ,
    acknowledged_at TIMESTAMPTZ,
    resolved_at TIMESTAMPTZ,
    resolution_type VARCHAR(30),
    resolution_summary TEXT,
    resolution_cause TEXT,
    resolution_actions TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_alerts_severity CHECK (severity IN ('CRITICAL', 'WARNING')),
    CONSTRAINT ck_alerts_status CHECK (status IN ('UNACKNOWLEDGED', 'ACKNOWLEDGED', 'ASSIGNED', 'IN_PROGRESS', 'UNDER_MAINTENANCE', 'RESOLVED')),
    CONSTRAINT ck_alerts_assignment_status CHECK (assignment_status IN ('UNASSIGNED', 'AWAITING_ACCEPTANCE', 'ACCEPTED', 'DECLINED', 'ESCALATED', 'REASSIGNED', 'COMPLETED')),
    CONSTRAINT ck_alerts_assignment_source CHECK (assignment_source IN ('AUTO_PRIMARY', 'ADMIN_ASSIGNMENT', 'BACKUP_CLAIM', 'NONE'))
);

CREATE TABLE alert_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id BIGINT NOT NULL REFERENCES alerts(id) ON DELETE CASCADE,
    event_type VARCHAR(50) NOT NULL,
    actor_name VARCHAR(150),
    details TEXT,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE alert_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id BIGINT NOT NULL REFERENCES alerts(id) ON DELETE CASCADE,
    user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    user_name VARCHAR(150),
    comment TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_alerts_status ON alerts(status);
CREATE INDEX idx_alerts_severity ON alerts(severity);
CREATE INDEX idx_alerts_fence_section ON alerts(fence_id, section_id);
CREATE INDEX idx_alerts_assignee ON alerts(assignee_user_id);
CREATE INDEX idx_alert_events_alert_id ON alert_events(alert_id);
CREATE INDEX idx_alert_comments_alert_id ON alert_comments(alert_id);
