-- User Notifications Inbox
CREATE TABLE user_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE,
    code VARCHAR(50) NOT NULL,
    title VARCHAR(200) NOT NULL,
    message TEXT NOT NULL,
    category VARCHAR(30) NOT NULL,
    fence_id BIGINT REFERENCES fences(id) ON DELETE SET NULL,
    section_id BIGINT REFERENCES sections(id) ON DELETE SET NULL,
    read BOOLEAN NOT NULL DEFAULT FALSE,
    channels VARCHAR(100),
    related_alert_code VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Generated Reports History
CREATE TABLE generated_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    template_id VARCHAR(50) NOT NULL,
    scope_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    generated_by_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    date_range_label VARCHAR(100),
    status VARCHAR(30) NOT NULL DEFAULT 'QUEUED',
    file_size VARCHAR(50),
    format VARCHAR(10) NOT NULL,
    file_path VARCHAR(500),
    generated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Support Tickets
CREATE TABLE support_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(254) NOT NULL,
    category VARCHAR(50) NOT NULL,
    subject VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    priority VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- FAQs
CREATE TABLE faqs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(50) NOT NULL,
    question TEXT NOT NULL,
    answer TEXT NOT NULL,
    display_order INT DEFAULT 0
);

-- User Profile Enhancements
ALTER TABLE users ADD COLUMN IF NOT EXISTS staff_id VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS contact_number VARCHAR(30);
ALTER TABLE users ADD COLUMN IF NOT EXISTS last_login_at TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS password_changed_at TIMESTAMPTZ;

-- User Notification Preferences
CREATE TABLE user_notification_preferences (
    user_id UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    sound_enabled BOOLEAN DEFAULT TRUE,
    desktop_notifications_enabled BOOLEAN DEFAULT TRUE,
    mark_as_read_on_open BOOLEAN DEFAULT TRUE,
    quiet_hours_enabled BOOLEAN DEFAULT FALSE,
    quiet_hours_start VARCHAR(10) DEFAULT '22:00',
    quiet_hours_end VARCHAR(10) DEFAULT '06:00',
    group_similar_notifications BOOLEAN DEFAULT TRUE,
    grouping_window_minutes INT DEFAULT 15,
    digest_enabled BOOLEAN DEFAULT FALSE,
    digest_interval_minutes INT DEFAULT 60,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_user_notifications_user_read ON user_notifications(user_id, read);
CREATE INDEX idx_generated_reports_user ON generated_reports(generated_by_user_id);
CREATE INDEX idx_support_tickets_user ON support_tickets(user_id);
